name: Deploy OCPP to Development Server

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup and build the project
      run: |
        npm install
        npm run build

    - name: Deploy with rsync from dist to the remote server
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: --mkpath --rsync-path="sudo rsync" --delete -avzr
        path: /
        remote_path: /home/ubuntu/ocpp_server
        remote_host: ${{ secrets.DEV_SERVER_DNS }}
        remote_user: ubuntu
        remote_key: ${{secrets.PRIVATE_ACCESS_KEY}}


    - name: Setup and build the project
      run: |
        ssh -i ~/.ssh/server_key ubuntu@${{ secrets.DEV_SERVER_DNS }} << 'EOF'
        sudo chown -R ubuntu:ubuntu /home/ubuntu/ocpp_server

        # spin-up nginx
        sudo nginx -t
        sudo systemctl restart nginx
        EOF
